name: a-table
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - Flask
  - requests
  - aiohttp
  - beautifulsoup4
  - ipython
  - pip:
          - Flask-Ask
          - cryptography<2.2
