name: a-table
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - Flask
  - requests
  - aiohttp
  - beautifulsoup4
  - pytest
  - pytest-cov
  - pytest-xdist
  - ipython
  - pandas
  - unidecode
  - pip:
    - Flask-Ask
    - cryptography<2.2
